//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveSpace.EngineController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.18")]
        public double FingerMinWidth {
            get {
                return ((double)(this["FingerMinWidth"]));
            }
            set {
                this["FingerMinWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.62")]
        public double FingerMaxWidth {
            get {
                return ((double)(this["FingerMaxWidth"]));
            }
            set {
                this["FingerMaxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.02")]
        public double FingerMinLength {
            get {
                return ((double)(this["FingerMinLength"]));
            }
            set {
                this["FingerMinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.74")]
        public double FingerMaxLength {
            get {
                return ((double)(this["FingerMaxLength"]));
            }
            set {
                this["FingerMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1505.62")]
        public double FingerRisingThreshold {
            get {
                return ((double)(this["FingerRisingThreshold"]));
            }
            set {
                this["FingerRisingThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1674.16")]
        public double FingerFallingThreshold {
            get {
                return ((double)(this["FingerFallingThreshold"]));
            }
            set {
                this["FingerFallingThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218.65")]
        public double ClickFloodMaxGrad {
            get {
                return ((double)(this["ClickFloodMaxGrad"]));
            }
            set {
                this["ClickFloodMaxGrad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int OmniTouchCroppingLeft {
            get {
                return ((int)(this["OmniTouchCroppingLeft"]));
            }
            set {
                this["OmniTouchCroppingLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int OmniTouchCroppingTop {
            get {
                return ((int)(this["OmniTouchCroppingTop"]));
            }
            set {
                this["OmniTouchCroppingTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OmniTouchCroppingRight {
            get {
                return ((int)(this["OmniTouchCroppingRight"]));
            }
            set {
                this["OmniTouchCroppingRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int OmniTouchCroppingBottom {
            get {
                return ((int)(this["OmniTouchCroppingBottom"]));
            }
            set {
                this["OmniTouchCroppingBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int DocRecognizerBinarizeThreshold {
            get {
                return ((int)(this["DocRecognizerBinarizeThreshold"]));
            }
            set {
                this["DocRecognizerBinarizeThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DocRecognizerCountdown {
            get {
                return ((int)(this["DocRecognizerCountdown"]));
            }
            set {
                this["DocRecognizerCountdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DocRecognizerVotesThreshold {
            get {
                return ((int)(this["DocRecognizerVotesThreshold"]));
            }
            set {
                this["DocRecognizerVotesThreshold"] = value;
            }
        }
    }
}
